# Description: This file is used to define the services that will be used in the application.
# Building; docker-compose build
# Running: docker-compose up -d
# Stopping: docker-compose down

name: jobtracker

include: 
  - path: 
    - ./database/docker-compose.yml

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend/api
    ports:
      - "5001:5001"

  db-init:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db-init/init-tables.sql:/init-tables.sql
      - ./db-init/init.sh:/init.sh
    command: ["/init.sh"]
    depends_on:
      - db