# Description: This file is used to define the services that will be used in the application.
# Building; docker-compose build
# Running: docker-compose up -d
# Stopping: docker-compose down

name: jobtracker
version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5001"